env:
  browser: true
  node: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:jest/recommended'
  - 'plugin:vue/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
parser: vue-eslint-parser
plugins:
  - '@typescript-eslint'
parserOptions:
  parser: '@typescript-eslint/parser'
  tsconfigRootDir: ./
  sourceType: module
  
rules:
  # Requires the use of single quotes for string literals
  quotes:
    - error
    - single
  jest/no-jasmine-globals: off

  '@typescript-eslint/camelcase': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/ban-ts-ignore': off

  # Allows to omit a return type
  '@typescript-eslint/explicit-function-return-type': 'off'
